version: "3"
#
services:
  db:
    image: postgres
    #importing the postgres image so we don't have to build it manually since the image is there anyway
    environment:
      POSTGRES_PASSWORD: csag
      POSTGRES_USER: commsultcloud
      POSTGRES_DB: shipments
      #Match this with what is in the db.js file
  app:
    image: nodejsbackendtest
    #name of app on docker
    ports:
      - 8080:3000
      #8989 is the port we access from the outside, 3000 is the port inside of the container. So when we connect to 8989, it redirects us to 3000 inside the container.
      #3000 is the port we exposed earlier in server.js
      #This is why our requests in the test.rest file is directed at 8080, and not 3000.
