###
GET http://localhost:8080
###
GET http://localhost:8080/setupdb
###

###
POST http://localhost:8080/
Content-Type: application/json

{
    "id": 1773,
    "destination":"Potsdam",
    "origin": "Manila",
    "status": "Preparing"
}
###