###
GET http://localhost:8989
###
GET http://localhost:8989/setupdb
###

###
POST http://localhost:8989/
Content-Type: application/json

{
    "id": 1773,
    "destination":"Potsdam",
    "origin": "Manila",
    "status": "Preparing"
}
###